name: "Terraform CI Check"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-ci:
    name: "Terraform Quality Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Chequeo de Formato (Lint)
        run: terraform fmt -check
        
      - name: Inicialización
        run: terraform init

      - name: Validación de Sintaxis
        run: terraform validate

      - name: Simulación de Seguridad para Plan/Apply
        run: |
          echo "CI completado con éxito: El código está formateado y la sintaxis es válida."
          echo "SEGURIDAD: Los pasos de 'terraform plan' y 'terraform apply' se omiten en este pipeline público."
          echo "En un entorno corporativo de producción, estos pasos se ejecutarían asumiendo un rol de IAM mediante autenticación OIDC (OpenID Connect) con AWS, evitando el uso de credenciales de larga duración."